title: Stackbit Fjord Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: yellow
header:
  title: Wohnzimmer e.V.
  tagline: Wohnzimmer e.V. Münster
  logo_img: images/wohnzimmer_logo.png
  logo_img_alt: Logo
  background_img: images/room-jockel.jpg
  has_nav: true
  nav_links:
    - label: Startseite
      url: /
      style: link
    - label: Fotos
      url: /about
      style: link
    - label: Vereinsmeierei
      url: /style-guide
      style: link
  has_social: true
  social_links:
    - label: Impressum
      url: /impressum
    - label: Datenschutz
      url: /datenschutz

footer:
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=fjord&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
