source "https://rubygems.org"

gem "webrick"
gem "jekyll-pig", path: "jekyll-pig-master"
gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
    gem "jekyll-menus", "~> 0.6.0"
    gem "jekyll-paginate-v2", "~> 1.9"
    gem "jekyll-paginate", "~> 1.1"
end
